require_op: true
verbose: true
bee_griefing: true
creeper_griefing: false
minecart_tnt_griefing: false
primed_tnt_griefing: false
ender_crystal_griefing: true
ender_dragon_griefing: true
enderman_griefing: true
falling_block_griefing: true
fireball_griefing: false
player_griefing: true
rabbit_griefing: true
ravager_griefing: true
sheep_griefing: true
snow_golem_griefing: true
frog_griefing: true
turtle_griefing: true
silverfish_griefing: true
villager_griefing: true
wither_griefing: false
wither_skull_griefing: false
zombie_griefing: true
zombie_villager_griefing: true
explosions_damage_players: false
