name: DisableMobGriefing
version: '${version}'
main: com.loyal0713.disablemobgriefing.DisableMobGriefing
authors: [Loyal0713]
api-version: '1.13'
description: Mod that allows for disabling mob griefing per mob instead of one global setting

commands:
  mobgriefing:
    description: Main command for DisableMobGriefing
    usage: /mobgriefing <mob> <true/false>
    aliases: [mg]
    permission: disablemobgriefing.command
    permission-message: You do not have permission to use this command!

permissions:
  disablemobgriefing.command:
    description: Allows use of the /mobgriefing command
    default: op
