name: DisableMobGriefing
version: '${version}'
main: org.loyal0713.disablemobgriefing.DisableMobGriefing
authors: [Loyal0713]
api-version: '1.15'
description: Mod that allows for disabling mob griefing per mob instead of one global setting

commands:
  mobgriefing:
    description: Main command for DisableMobGriefing
    usage: /mobgriefing <mob> <true/false>
    aliases: [mg]
    permission-message: You do not have permission to use this command!
